Repository apple/swift-protobuf, pull requests merged in 2025-08, with the labels that each got.

#1822 Add expected failures for the new conformance test issues.
  Sources/Conformance/failure_list_swift.txt
Labels: semver/none

#1823 Validate Duration before generating JSON to match upstream.
  Sources/Conformance/failure_list_swift.txt
  Sources/SwiftProtobuf/Google_Protobuf_Duration+Extensions.swift
  Tests/SwiftProtobufTests/Test_Duration.swift
Labels: 🆕 semver/minor

#1825 Support "edition2024".
  Makefile
  Sources/SwiftProtobufPluginLibrary/PluginLibEditionDefaults.swift
  Sources/protoc-gen-swift/SwiftGeneratorPlugin.swift
  Tests/SwiftProtobufPluginLibraryTests/PluginLibTestingEditionDefaults.swift
Labels: 🆕 semver/minor

#1835 Add automated protoc artifact bundle generation for releases
  .github/scripts/upload_artifactbundle.sh
  .github/workflows/prerelease_protoc_artifactbundle.yml
  Documentation/RELEASING.md
Labels: 🔨 semver/patch

#1837 Create separate protoc releases
  .github/scripts/draft_release_protoc_artifactbundle.sh
  .github/workflows/draft_release_protoc_artifactbundle.yml
  .github/workflows/prerelease_protoc_artifactbundle.yml
  Documentation/RELEASING.md
Labels: semver/none

#1844 Add support for our use of `package` visibility.
  SwiftProtobuf.podspec
Labels: semver/none
